### ISSUE TITLE
Unintended?: Friendly fire kicks

### ISSUE THREAD

**Issue by Furrior** [IntQuant/noita_entangled_worlds#1]
You can kick another player and they will drop all their items. Probably a feature from noita arena that shouldnt work in coop.

**Comment by IntQuant** [comment]
This is actually a vanilla mechanic, used to [make enemies drop wands](https://www.reddit.com/r/noita/comments/vzsasv/helpful_tip_of_the_day_kicking_enemies_makes_them/). I'm not sure if I can turn that off.

Besides, it's kinda funny.

**Comment by EvaisaDev** [comment]
> This is actually a vanilla mechanic, used to [make enemies drop wands](https://www.reddit.com/r/noita/comments/vzsasv/helpful_tip_of_the_day_kicking_enemies_makes_them/). I'm not sure if I can turn that off.
> 
> Besides, it's kinda funny.

in case you haven't figured this out yet, there is a component value somewhere that disables item dropping on kicks, i had to disable it for arena.

**Comment by Furrior** [comment]
I would try to fix this myself, but havent succeeded in running both client and host on the same system and don't want them to use different versions of the mod and proxy with just tweaked ports. If Im stupid and it's actually doable - would be nice to create a contributing.md and add the guide there.

**Comment by IntQuant** [comment]
I was simply using two computers, but maybe I can use SO_REUSEADDR to allow launching several proxies at once, while still using the same port? I'll try it now.

**Comment by IntQuant** [comment]
I ended up using environmental variables to specify a different address. It's described in contributing.md.

**Comment by EvaisaDev** [comment]
> > This is actually a vanilla mechanic, used to [make enemies drop wands](https://www.reddit.com/r/noita/comments/vzsasv/helpful_tip_of_the_day_kicking_enemies_makes_them/). I'm not sure if I can turn that off.
> > Besides, it's kinda funny.
> 
> in case you haven't figured this out yet, there is a component value somewhere that disables item dropping on kicks, i had to disable it for arena.

specifically `is_immune_to_kicks="1"` on ItemPickUpperComponent iirc

**Comment by IntQuant** [comment]
Thanks, that works.
