### ISSUE TITLE
notplayer kick should do more damage and stun

### ISSUE THREAD

**Issue by bgkillas** [IntQuant/noita_entangled_worlds#102]

**Comment by IntQuant** [comment]
Maybe, but that would make stats different from a base player, which would make it less predictable, so I'd like to avoid it. if possible. A better ai would likely make close combat less frequent.

Oh and I think notplayer currently doesn't kick ever, should probably change that.

**Comment by bgkillas** [comment]
yeah i guess making so he doesn't back himself in a wall would also work

**Comment by bgkillas** [comment]
i made so he doesn't backhimself in a wall stupidly in latest release so closing
