### ISSUE TITLE
in local mode While dead your doppelganger will pick up wands and they cease to exist

### ISSUE THREAD

**Issue by Mentaleak** [IntQuant/noita_entangled_worlds#105]
in local mode While dead your doppelganger will pick up wands and they cease to exist

**Comment by bgkillas** [comment]
i think this is also true for potions

**Comment by TTViri** [comment]
This is true for many objects that are able to be picked up, in my experience.
Including:
 - Pouches
 - Wands
 - Spells
 - Tablets
 - Elemental Rocks
 
This is just things that I have directly observed, it could happen with more.

**Comment by bgkillas** [comment]
fixed in latest release
