### ISSUE TITLE
Can workshop mods be used, or is this vanilla only?

### ISSUE THREAD

**Issue by TheSpiderDungeon** [IntQuant/noita_entangled_worlds#110]
Modding is the only concern I have about Entangled Worlds; everything is made incredibly well, and I'm very impressed, but I can't find any info about mods anywhere.

**Comment by bgkillas** [comment]
depends on the mod https://docs.google.com/spreadsheets/d/1nMdqzrLCav_diXbNPB9RgxPcCQzDPgXdEv-klKWJyS0

**Comment by TheSpiderDungeon** [comment]
Perfect, thanks!
