### ISSUE TITLE
Chest and angry ghost bug report

### ISSUE THREAD

**Issue by SamuelDev** [IntQuant/noita_entangled_worlds#115]
Host sees all chests but connected clients cant seem to see any chests.

Angry ghost hurts all players except the player that took angry ghost.

**Comment by SamuelDev** [comment]
Follow up to angry ghost: this means it can provide infinite healing bolt to everyone, but the negative of being hurt by it outweighs that benefit in my opinion.

**Comment by bgkillas** [comment]
i disabled it for the next release for now, i think the chest thing is just physics objects sync not being a thing, maybe will be fixed in next release
