### ISSUE TITLE
Proxy will not open connection window

### ISSUE THREAD

**Issue by Declan12k** [IntQuant/noita_entangled_worlds#12]
Windows indicates that both the command prompt and the connection window are both open. However, the connection window remains invisible and the command prompt stays stuck on "Creating the app"

![image](https://github.com/IntQuant/noita_entangled_worlds/assets/114784085/9f8555d0-d93c-498b-929d-11ac85accaaa)

**Comment by IntQuant** [comment]
Could this be the same as #3 ?

**Comment by Declan12k** [comment]
> Could this be the same as #3 ?

It was the same issue! Thank you for linking me that thread, I didn't see it on my end.
