### ISSUE TITLE
consistent world object desync across clients

### ISSUE THREAD

**Issue by gabrielkyle** [IntQuant/noita_entangled_worlds#122]
player 1 (host) ![image](https://github.com/user-attachments/assets/c048ce90-6296-4f5a-9b0e-cfd0aa08f3b2)
player 2 ![image](https://github.com/user-attachments/assets/f0c159d9-c2e6-42a6-ae75-cb3d970940e3)

player 1 (host) ![image](https://github.com/user-attachments/assets/cf3e0501-f789-4caf-bea1-1fee0892372b)
player 2 ![image](https://github.com/user-attachments/assets/d1611c64-e503-4353-b558-8ee87cf77f30)

player 1 (host) ![image](https://github.com/user-attachments/assets/ffc04d4c-73af-4e3a-9ea0-6225ed1d2f8e)
player 2 ![image](https://github.com/user-attachments/assets/be6f77af-2527-424f-92c2-0ed310c7f319)

consistently seems to be most world objects are up and to the left of the 2nd player client compared to the host client.

**Comment by gabrielkyle** [comment]
notably didn't happen before the worldsync update a few major patches ago

**Comment by bgkillas** [comment]
1st bit is just because we dont sync multi-part object, 2nd and 3rd, i dont get, aspecially since you say "worldsync" from a few major patches ago, it wasn't synced until a bit ago

**Comment by gabrielkyle** [comment]
> 1st bit is just because we dont sync multi-part object, 2nd and 3rd, i dont get, aspecially since you say "worldsync" from a few major patches ago, it wasn't synced until a bit ago

Yeah, that's what i'm referring to, i don't remember exactly when it happened which is why i just said a few major patches ago, but by major patches i'm talking 0.XX. updates, since they seem to have fairly large changes. anyways, i'm not sure what would be the cause of it, but it's consistently up and to the left for second client.

**Comment by bgkillas** [comment]
is this steam connect?

**Comment by gabrielkyle** [comment]
Correct, steam connect, the settings for the server are below
![image](https://github.com/user-attachments/assets/d41cff69-a298-4e57-9107-d1200a0e3ef6)

**Comment by gabrielkyle** [comment]
Oh, Update, I found out it was due to player 2's ini settings changing the "resolution" of the game, essentially zooming in the game on their end slightly.  I'm not sure if this is something that can be fixed but it was due to a mismatch of our game screen size.

**Comment by chloelcdev** [comment]
I can confirm we're having the same issue with a slightly different (but consistent) offset. I'll try to test tonight if we can fix it by matching resolutions and I'll check back in.
