### ISSUE TITLE
Game fails to initialize mod quant.ew upon starting a new game

### ISSUE THREAD

**Issue by Declan12k** [IntQuant/noita_entangled_worlds#13]
Mod is enabled, and mod settings are set to connect rather than host. The proxy window shows that I have connected to the host's party and is awaiting a new game. Once loaded in, the game sends and error message in the lower left hand that quant.ew failed to initialize.

My console:
![image](https://github.com/IntQuant/noita_entangled_worlds/assets/114784085/aa4fab93-a945-4016-9db5-8c5ad776900b)

Host's console:
![image](https://github.com/IntQuant/noita_entangled_worlds/assets/114784085/87d35b2e-db93-4026-8957-22ea131ef55b)

**Comment by GrahamKowalski** [comment]
Changing in-game mod settings to 'connect' and adding host IP to mod settings may fix this.

**Comment by Declan12k** [comment]
> Changing in-game mod settings to 'connect' and adding host IP to mod settings may fix this.

Thanks, this solved my problem!

**Comment by IntQuant** [comment]
For anyone else having this issue, see [here](https://github.com/EvaisaDev/noita-online/issues/8) for a probable cause.

Otherwise, I'm closing this issue.
