### ISSUE TITLE
 Failed to create Zip Archive reader

### ISSUE THREAD

**Issue by Mentaleak** [IntQuant/noita_entangled_worlds#130]
V0.21.3

Encountered an error: 
 Failed to create Zip Archive reader

Caused by:
    invalid Zip archive: No valid central directory found

Location:
    src/bookkeeping/mod_manager.rs:355:48
    
    I received this error after updating. 
    I received it after downloading manually and extracting.
    I received it when running as administrator
    
   "mod.zip" exists in the extracted folder next to the noita_proxy.exe

**Comment by IntQuant** [comment]
Marked that version as pre-release for now.
The zip library refuses to open that zip file for some yet unknown reason.

**Comment by IntQuant** [comment]
Should be fixed in 0.21.4
