### ISSUE TITLE
Proxy launcher on linux is too large for the Steam Deck

### ISSUE THREAD

**Issue by restt** [IntQuant/noita_entangled_worlds#131]
Hello! I play all my games on the steam deck and it seems i have an issue with the launcher window
![Screenshot 2024-08-23 20-25-39](https://github.com/user-attachments/assets/fefb7319-c8b6-492a-b98e-63baa0c57257)

the window is so large that i can't select any options on the deck, i assume due to being designed for the resolution size of a regular monitor. Issue is that it also doesn't let me resize it, or i assume it's probably already the smallest size option for a regular PC that is still too large for a steam deck.

any particular workaround for people who own a steam deck?

**Comment by IntQuant** [comment]
Proxy has `--ui-zoom-factor` argument. Try to add `--ui-zoom-factor 0.1`  or something like that and check how it goes.

**Comment by IntQuant** [comment]
Hmm, it also looks like the window doesn't quite fit. Which is weird, because the minimum size is set to 800 by 600, and steam deck has enough resolution for that.

It's a bit problematic to test because I don't have a steam deck. I will, hovewer, try to implement more command-line option in hopes that they will work at some point.

**Comment by bgkillas** [comment]
you can use gamescope to emulate resolutions easily

**Comment by IntQuant** [comment]
Gamescope segfaulted on my system last time I checked, so... yeah.

**Comment by restt** [comment]
> Proxy has `--ui-zoom-factor` argument. Try to add `--ui-zoom-factor 0.1` or something like that and check how it goes.

uhh.. so of course, as a fellow proficient linux user who myself knows many great commands and is very knowledgeable of the inner workings of running scripts and lines via its terminal (or konsole in steam deck's case).. hypothetically speaking, imagine that i am just a former windows person that just bought a steam deck not too long ago and has no idea how any of this linux stuff works hahaha, which would be very silly but it's only a hypothetical of course haha... and with that in mind:
 
- how does one in that position run the program with that argument? what exactly does he need to input and where? one would assume in the konsole?
- since he only wants to play games on it and has no idea what this gamescope thing is, as he just installs all his things via the Discovery thing, happens to find the gamescope thing there, installed it, then ran a "gamescope --help". Due to the overwhelmingly amount of commands shown, how does one emulate a resolution in it for desktop mode, what's the specific command (and preferably to turn it back so he doesn't get stuck)

out of the two options, the quickest and easiest one would suffice as an answer. This is of course only within the realm of this hypothetical version of myself that has zero clue how any of it works hahaha, which is totally not the actual me, the very proficient linux user.

**Comment by IntQuant** [comment]
The gamescope thing was referring to a way to test things without a physical steam deck, so don't think about it too much.

Then, a theoretical former windows person would open a terminal (looks like you've managed to find it). Then you move your current directory to one where proxy is located (you can write `cd <path>` to do that), and then start proxy like that: `./noita-proxy --ui-zoom-factor 0.1`

![Screenshot_2024-08-23_22-53-11](https://github.com/user-attachments/assets/9374de91-35c7-4155-a8b9-41dceae618c7)

**Comment by restt** [comment]
now would you look at that 
![Screenshot 2024-08-23 22-57-40](https://github.com/user-attachments/assets/d1363b43-e7bb-4ef7-93eb-eaee9d2dd3f9)

it did seem to work quite well, obviously i knew how to do that, i was only testing to see if you knew too.

myself, the elite linux connoisseur that is very obviously skilled in running scripts, is very thankful for helping this hypothetical version of me that prefers to be spoon fed like baby. I'll be closing this issue as solved.

**Comment by IntQuant** [comment]
@restt could you share the value of ui-zoom-factor that you ended up using? I'll look into making it default on steam deck.

**Comment by restt** [comment]
yup, i used --ui-zoom-factor 0.3 which should launch the application on their steam deck screen looking like this
![Screenshot 2024-08-23 23-17-55](https://github.com/user-attachments/assets/468e409a-ea33-438f-b511-43d205c47c7c)

**Comment by IntQuant** [comment]
@restt Last release should set that ui scale on Steam Deck automatically on launch, an extra parameter shouldn't be necessary anymore.
