### ISSUE TITLE
Client and/or host unable to control character.

### ISSUE THREAD

**Issue by AbsoluteAndrew** [IntQuant/noita_entangled_worlds#132]
This started happening several hours into the best run my brother and I have ever had. We saved and quit for a break, and when we came back and booted it up like we always do, one or both of us could no longer move our respective character. WASD wouldn’t work, and the camera was slightly off center from us like it didn’t even know we were in the world. I say it happened to both of us because I could not get this issue to go away after numerous reboots, entire re-installations of the entangled worlds mod on both our ends, switching who was the host, etc.

Odd thing is, many times you could still swap your wands and items in your hand. The game was not froze. At all. Just you. Also moving the mouse around usually did move the aiming crosshair, but your noita would not aim his item or wand towards it in any way like they are supposed to. Nor could you fire a wand of throw anything. Just swap between them. We are leaving this run saved in hopes of a fix ;(

**Comment by robbplo** [comment]
Same thing happened to me and my brother last night, crazy coincidence!

We were 1 parallel world to the east, and the game was starting to get unstable and laggy. After restarting we were not able to move, but like you said we could still swap wands. I was the host, and after hitting escape a few times I was able to move again, but this did not work for my brother.

Did not see any particular warnings or errors, other than save file being >50mb. Is there a log file or something we could share?

**Comment by petrnymsa** [comment]
Happened to us same thing

**Comment by petrnymsa** [comment]
SOLVED or maybe workaround. 
QUIT noita.


Open Player.xml - on Windows located at `C:\Users\USERNAME\AppData\LocalLow\Nolla_Games_Noita\save00` 

Find `ControlsComponent` 


```xml
 <ControlsComponent 
    _enabled="1" 
    enabled="0" 
    gamepad_fire_on_thumbstick_extend="0" 
    gamepad_fire_on_thumbstick_extend_threshold="0.9" 
    gamepad_indirect_aiming_enabled="0" 
    polymorph_hax="0" 
    polymorph_next_attack_frame="0" >
```
and change `enabled="0"` to `enabled="1"`.  

Start session. You should be able to move

**Comment by bgkillas** [comment]
fixed probably
