### ISSUE TITLE
Kolmi issues

### ISSUE THREAD

**Issue by SeroRonin** [IntQuant/noita_entangled_worlds#14]
Played through a run with a friend, mod works far better than we anticipated, albeit a few expected issues.

I don't know if it was the specific order we picked up the Sampos, or if it was because Host never hit the boss (Client wanted to one-shot it), but we ran into two issues at the Kolmi fight.

After picking up the Sampo, Kolmi was either invisible or still idle on the client side, while active on the host side. Client was still able to hit and kill Kolmi by aiming where it was supposed to be though.

Additionally, killing Kolmi didn't spawn the portal to the work for either of us.

**Comment by bodashka** [comment]
I don't think the mod developer thought that anybody would actually complete the game :D

**Comment by IntQuant** [comment]
Fixed, will be released in v0.14
