### ISSUE TITLE
Client Holy Mountain Teleport Issue

### ISSUE THREAD

**Issue by GrahamKowalski** [IntQuant/noita_entangled_worlds#15]
Bug with client taking portals to holy mountains. Teleport seems to vary where it places the clients. No issues with host holy mountain. Multiple games teleported into holy mountain bricks. Forces a game restart.

![holymountain](https://github.com/IntQuant/noita_entangled_worlds/assets/79672667/d48b23f4-1ee5-45ee-ac2a-87fe9e196e59)

**Comment by IntQuant** [comment]
It seems to work better when host goes first.
