### ISSUE TITLE
Sometimes the host or other players cannot see the items in the spell store

### ISSUE THREAD

**Issue by LuoTianOrange** [IntQuant/noita_entangled_worlds#157]
![47cc1cf9-d2f7-4ac0-9f1a-b37e7d61ceea](https://github.com/user-attachments/assets/e8bf10ce-76af-47fe-a982-7dd519429155)

**Comment by LuoTianOrange** [comment]
![正在上传 76dae3b577bc08f7564652a892c2fef1.png…]()

**Comment by LuoTianOrange** [comment]
![76dae3b577bc08f7564652a892c2fef1.png](https://github.com/user-attachments/assets/62757de3-75c8-4aec-a33d-55993625d4e2)

**Comment by bgkillas** [comment]
i think this has been fixed
