### ISSUE TITLE
Player in the lobby (not host) gets the pacifist chest even when both aren't doing a pacifist run.

### ISSUE THREAD

**Issue by 1DarkLight1** [IntQuant/noita_entangled_worlds#16]
Everytime I enter a mountain, only I, not the host, keep getting the pacifist chest. We both kill enemies on our way but I still tend to get a pacifist chest in each and every mountain.

**Comment by apeckdev** [comment]
For me both host/client get the pacifist chest. Also the host was getting double gold on every kill and trick blood money made enemies drop blood money on every kill on the host side. On the client side it seemed to be impossible to get trick kills.

**Comment by IntQuant** [comment]
> For me both host/client get the pacifist chest. Also the host was getting double gold on every kill and trick blood money made enemies drop blood money on every kill on the host side. On the client side it seemed to be impossible to get trick kills.
> 
> Edit There's a closed issue about the double gold #4

Are you using v0.3.0?

**Comment by apeckdev** [comment]
This was on v0.2.0

**Comment by 1DarkLight1** [comment]
> This was on v0.2.0

Yeah the issue is already fixed by now I'm sure. ^-^

**Comment by AlfredKhachatryan** [comment]
Same issue here
