### ISSUE TITLE
noita_proxy.exe не запускается

### ISSUE THREAD

**Issue by 44Corvus44** [IntQuant/noita_entangled_worlds#165]
←[2m2024-09-21T15:08:42.202495Z←[0m ←[32m INFO←[0m ←[2mnoita_proxy←[0m←[2m:←[0m None
это сообщение возникает в консоли при запуске
причем если не успеть тыкнуть по консоли, то она моментально закроется, а окно так и не создастся
ранее эта проблема была описана в #3 и #12, но метод от них мне не помог

причем одинаково на пиратской и стимовской версии

**Comment by IntQuant** [comment]
Если в первый раз работало нормально, но не открывается в следующие разы, можно попробовать удалить конфиг по пути %APPDATA%\Roaming\noita-proxy

**Comment by 44Corvus44** [comment]
> Если в первый раз работало нормально, но не открывается в следующие разы, можно попробовать удалить конфиг по пути %APPDATA%\Roaming\noita-proxy

с самого начала он отказался работать нормально, уже несколько раз переустанавливал и купил стимовскую версию noita, все без толку

**Comment by IntQuant** [comment]
А что-нибудь ещё пишет? Можно сначала открыть cmd, и в нём уже открыть прокси.

**Comment by 44Corvus44** [comment]
> А что-нибудь ещё пишет? Можно сначала открыть cmd, и в нём уже открыть прокси.

←[2m2024-09-24T18:33:58.664543Z←[0m ←[32m INFO←[0m ←[2mnoita_proxy←[0m←[2m:←[0m None
Error: Glutin(Error { raw_code: None, raw_os_message: None, kind: NotSupported("extension to create ES context with wgl is not present") })
вот что пишет

**Comment by IntQuant** [comment]
Сильно старые драйвера/видеокарта (> 13 лет). Возможно позже придумаем решение, поскольку есть неожиданно много людей с такой проблемой, но это довольно нетривиально.

**Comment by artginzburg** [comment]
Got the same message. Also tried just opening cmd and then proxy, with no luck. Maybe that's because I'm on Mac via CrossOver w/ Windows 7. Going to try newer versions of Windows, and earlier versions of the mod. If that does not work — going to try Parallels or VMware Fusion, and post back here

**Comment by Tingel24** [comment]
@artginzburg Did you have any success getting the mod running on MacOS?
