### ISSUE TITLE
several desync bugs on long run while doing sun quest

### ISSUE THREAD

**Issue by QueenOfKelp** [IntQuant/noita_entangled_worlds#166]
1) Only I could see sun eggs. I was the host and also created the sun eggs so not sure which of those let me see them. other player could see the suns that already existed in the moon and dark moon

2) while breaking the perk rerollers some of them (between 1 and 4 which was different for both players) seemingly were completely de-loaded so when going back to them the second time they had extremely high costs instead of 200

3) around the 7 hour mark some permanent terrain bugs occurred such as random masses of cursed rock being strewn across the main world as well as sections of desert biome in the ice biome and vice versa. The paha sima was also wasn't visible or pick up able on the host's screen. These issues were initially only present on the host's screen. we went to NG+ and the problems went away.

4) essence eater worked as expected once but the second time the essence was only removed from me when I destroyed it.

in total the run lasted 8.5 hours and about 15 parallel worlds were loaded to give context for how much stress the game was under.
we've only done 1 long run with this mod so far so I'm not sure how consistent these issues are

**Comment by IntQuant** [comment]
1. Sun quest isn't synced yet.
2. I don't have much to say about this right now. Not very familiar with how breaking perk reroll machines works.
3. Were you playing with tether off and with players being multiple PWs apart?
4. Essence eaters aren't actually synced, it just happened to be removed because you were also seen shooting at it on the other client's side.

**Comment by QueenOfKelp** [comment]
> 1. Sun quest isn't synced yet.
> 2. I don't have much to say about this right now. Not very familiar with how breaking perk reroll machines works.
> 3. Were you playing with tether off and with players being multiple PWs apart?
> 4. Essence eaters aren't actually synced, it just happened to be removed because you were also seen shooting at it on the other client's side.

for 2 what happens is you have to load 39 perk machines in the game at a low price and then they will keep that same low price as you go back to each perk machine and reroll them. because the price of rerolling increases exponentially but each perk machine was already loaded and will have the low price regardless of what the current reroll price is you can keep rerolling until eventually the machine does a weird overflow thing because of the "correct" reroll price still being stored and increased and this allows you to reroll perks hundreds of times for basically free. Because I was host and individually visited each machine I know for a fact that I should have loaded them all but for some reason one of them had an extremely high price when I came back (and for my friend this machine had the expected price of 200 so I doubly know that I should have loaded in that machine on my screen), for my friend it's technically possible that a few of the machines were never loaded in the first place but it seems unlikely. My assumption is that this mod somehow unloaded a few perk machines so that the game never stored their low price to begin with which allowed them to be highly priced because I've never personally seen this happen in vanilla. honestly it's not even remotely a high priority fix because we can just load some extra machines to be careful but I figured I'd mention it here in case you find a solution.

for 3 we were playing with tether on and were at most 1 parallel world apart ( and really probably more like .1 parallel worlds apart since we weren't on opposite ends or anything). I will say that there were a few times (particularly when entering the tower idk if this is a coincidence) where the tether seemed to not work and he wasn't teleported to me so if this is a known issue then I suppose it might have just been a problem with the tether being jank idk.

for 4 I will just say that my friend said he couldn't see the essence eater on his screen in the first place but 1) he is blind and 2) I assume it's already a well known issue that sometimes objects in the world don't spawn perfectly when the mod is already being stretched to its limits so that's just a rip

just wanted to say btw that I love this mod
