### ISSUE TITLE
'Edit wand at any time' stops working after player respawn

### ISSUE THREAD

**Issue by LuoTianOrange** [IntQuant/noita_entangled_worlds#167]
Both the effects provided by "Edit Wands Always" and "Spell Labs" will stop working after respawn.

**Comment by trollocat** [comment]
Can confirm. Tested "Edit Wands Always" for a 3 player lobby and exactly every time someone dies and revives, the edit wand anywhere perk stops working for the rest of the run, even tho it appears as you still have it

**Comment by LuoTianOrange** [comment]
At present, when a player dies, they will lose the 'edit wand at always' effect. When using the Spell Labs to add a layer of effect, the ability to 'edit wand at always' is restored.

**Comment by bgkillas** [comment]
prob fixed next update whenever quant feels like releasing
