### ISSUE TITLE
Steam networking Could not init steam networking: Some other failure

### ISSUE THREAD

**Issue by SuniK0** [IntQuant/noita_entangled_worlds#168]
Display that Steam networking Could not init steam networking: Some other failure.
how can i fix this problem?
![15C92270FA2A2785E15821F948574EB0](https://github.com/user-attachments/assets/c0a40616-df03-473b-9fa5-bb3161f18424)

**Comment by IntQuant** [comment]
Either steam isn't running (has to be open before proxy is started), or you don't own the game on steam.
