### ISSUE TITLE
[Suggestion] Some kind of Anti Piracy

### ISSUE THREAD

**Issue by NameLord** [IntQuant/noita_entangled_worlds#169]
like connecting the Noita Proxy with Steam Account and verify if the game is bought, if game is not on their steam account close the Proxy. Don't let them play with something that you've been working hard for idk ? 4 months, don't let them thing everything is free......
As for why ? Like... Do you like cracking/pirating ? If no then this might be a good idea to implement..

**Comment by bgkillas** [comment]
how do we tell if everyone has a gog install, or itch install, way to stupid and annoying, or if 1 person owns the game and gives it to their friends(imo totally fine) idc

**Comment by da3dsoul1** [comment]
One of the stupidest issues I've seen on github no cap
