### ISSUE TITLE
Fungal shift needs to be synced

### ISSUE THREAD

**Issue by 1DarkLight1** [IntQuant/noita_entangled_worlds#17]
So this should be obvious and okay. I ate fungal (as a player, not host) and my lava switched to oil. However, when I jumped in this "oil", we instantly died from lava. I think that's because only host's liquids/shift matters.

**Comment by IntQuant** [comment]
Yes, fungal shift isn't synced yet

**Comment by IntQuant** [comment]
Completed in v0.10.0
