### ISSUE TITLE
Player selling wands using pheromones gives lots of money

### ISSUE THREAD

**Issue by 1DarkLight1** [IntQuant/noita_entangled_worlds#18]
So, host selling wands works okay (though the player doesn't get any money for some reason), as host gets reasonable cash. But, when player sells wands, it gets both the player and the host like 600 or 800 gold for ANY wand sold, and it's stats doesn't even matter.

**Comment by Midasmithril** [comment]
I've found that this issue can easily stack up with [this](https://github.com/IntQuant/noita_entangled_worlds/issues/23#issue-2306264472) issue here, leading to the wand not disappearing on one side and being turned into gold on the other side
me and my friend got through a few cycles while laughing his head off at how powerful this was before he(host) crashed and lost the save

**Comment by bgkillas** [comment]
i think this is fixed, gold may apear on both sides still depending on how you sell it but i dont get extra gold
