### ISSUE TITLE
Glass Cannon & Shared Health

### ISSUE THREAD

**Issue by NameLord** [IntQuant/noita_entangled_worlds#181]
Have noone in this universe found this ? like.... i just found out days ago and i just waited for someone to report it but NOONE did...
in local health yes.. it does decrease health. But in Shared, it doesn't soo 100% Pick rate on glass cannon every-time when i play it :) until it gets fixed of course.

**Comment by IntQuant** [comment]
Not really mentioned anywhere aside from patch notes for a certain version, but in shared health it makes you GET 5 times as much damage as well.

**Comment by NameLord** [comment]
> Not really mentioned anywhere aside from patch notes for a certain version, but in shared health it makes you GET 5 times as much damage as well.

Soo its not a bug anymore right ?

**Comment by bgkillas** [comment]
? it was fixed months ago by the method he stated, it would be silly to make everyone go down to 50 hp because 1 person took glass cannon, maybe it should do more then 5x damage though, like maxhp/50hp times damage

**Comment by NameLord** [comment]
Arlight then, thank you.
You can close this Issue post by now.
