### ISSUE TITLE
Sometimes I can't see my teammates' bombs while online

### ISSUE THREAD

**Issue by shan-shen-ye** [IntQuant/noita_entangled_worlds#183]
When teammates use wands to release various bombs, they become invisible and cannot see the bombs, which can easily harm teammates

**Comment by bgkillas** [comment]
is this after using spell refreshes? you kind have to open and close your inventory for spell refresh to sync

**Comment by shan-shen-ye** [comment]
> 这是在使用法术刷新之后吗？您必须打开和关闭您的库存才能同步法术刷新

The initial wand bomb can sometimes be invisible, and I feel like there is a chance to see the invisible bomb in each level
