### ISSUE TITLE
Удалённый хост принудительно разорвал подключение (os error 10054)

### ISSUE THREAD

**Issue by Sergnovo** [IntQuant/noita_entangled_worlds#184]
В определённый момент начинает кикать из игры, но не из лобби, каждый раз, когда я перезахожу - кикает спустя 10-15 секунд и так до бесконечности

**Comment by Sergnovo** [comment]
Перепробовал всё что можно, ничего не помогает. Помогите если кто знает как пофиксить

**Comment by IntQuant** [comment]
Windows 11?

Была рекомендация написать `netsh winsock reset` в cmd и перезапустить систему, но не уверен, будет ли оно работать.

**Comment by bgkillas** [comment]
#197 ?
