### ISSUE TITLE
Revenge rats seem to damage yourself when friendly fire is enabled.

### ISSUE THREAD

**Issue by Vinjul1704** [IntQuant/noita_entangled_worlds#185]
It seems like the revenge rats perk causes the spawned rats to attack and kill you when friendly fire is enabled.

**Comment by bgkillas** [comment]
i assume your client right? if so this is unfixable to my knowledge from lua side

**Comment by Vinjul1704** [comment]
> i assume your client right? if so this is unfixable to my knowledge from lua side

Do you mean if they only attack the person with the perk? Then yes, that seems to be the case.

**Comment by bgkillas** [comment]
id assume it only attacks non hosts, i guess there could be workaround if that is the case

**Comment by bgkillas** [comment]
finally got around to just disabling the perk with ff on
