### ISSUE TITLE
Idk if this is a issue or is it really done by the done develober but pls answer

### ISSUE THREAD

**Issue by viljoOlen** [IntQuant/noita_entangled_worlds#186]
Why some perks are banned? 
like gravity kick and angry ghost?
me and my friend been playing loooooong and not found any of those 2

**Comment by viljoOlen** [comment]
nvm

**Comment by LuoTianOrange** [comment]
![4RYT7PF2@H@UAZ6ETQ3L9IP](https://github.com/user-attachments/assets/5c866fbb-686e-4847-beb2-ca9145367277)
We have seen 'angry ghost' before，in software version 0.26.0

**Comment by bgkillas** [comment]
#116
