### ISSUE TITLE
Clients become invisible to each other and can’t affect each other when connect using IP

### ISSUE THREAD

**Issue by RobinLuFae** [IntQuant/noita_entangled_worlds#188]
We have 3 players, one of us creates a server as a host, the other two connect to host’s IP as clients, then we enter the game.
	The host can see, and get harmed by 2 clients correctly ( We enabled friendly fire ), but from a client’s perspective, he can only see host’s character and can only get harmed by host, another client’s character looks completely invisible to him while an id float in air, and he can’t get harmed by another client’s spells at all ( The spells are also invisible or nonexistent for him)
	In a word, a client can only “feel” another client’s presence when another client breaks the terrain, grabs items or wands and kills enemies. Yes, we still share same enemies, so in a client’s perspective, many enemies just suddenly died and gold appeared, although the floating id of another client indicated who just killed them.
	Our settings are the same as the picture down there, is there anything wrong that caused this issue? We really want to connect using IP, because there is severe lag when using Steam and the connection always breaks after each several minutes so we have to restart noita_proxy very frequently and can hardly play normally . Since we 3 people are in the same room, connect using IP will hardly cause any lag.
	Anyway, we appreciate this mod and its author very much for it allowed us to play together. If our problem is because this function is not fully developed yet, we will wait for it, otherwise we want to know the reason and solve it.
![QQ20241012-213326](https://github.com/user-attachments/assets/aaf9acfc-96ad-4808-a11b-bd9940dc9dc2)

**Comment by bgkillas** [comment]
your not meant to format plain text like that, just dont use ip connect, its very much worse, steam connect can be done even without steam noita anyways

**Comment by IntQuant** [comment]
Just to make sure:
Everyone sees nicknames of other players, but not the player "visuals"?

**Comment by IntQuant** [comment]
For a somewhat temporally solution, this might work:

Copy all contents from host from `<noita folder>/mods/quant.ew/files/system/player/tmp` and `<noita folder>/mods/quant.ew/data/generated` to same location on other clients.

So for three players this folder should look something like that on every computer:
![image](https://github.com/user-attachments/assets/49c87bf2-12bc-42bf-96d4-86ea338eba69)

It seems like there is some issue with these files being generated, but you can just manually create them this way.

**Comment by IntQuant** [comment]
Should be fixed in the next release.
