### ISSUE TITLE
Unable to start as a server on Ubuntu

### ISSUE THREAD

**Issue by zxbly-pro** [IntQuant/noita_entangled_worlds#189]
I want to start a server on Ubuntu to connect to the window client, but I found that starting requires GLIBC version 2.39. Currently, I have found the highest source version to be 2.35
![11](https://github.com/user-attachments/assets/e1e11354-ce0c-46c6-b411-8bdd7f08e8b5)
ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
I am using Ubuntu 20.04 Desktop (amd64)

**Comment by rasm685p** [comment]
You could always try to download Glibc directly from the source instead of the Ubuntu package manager. Packages on Linux distros often seems to be out of date.

**Comment by bgkillas** [comment]
or just build it yourself, cargo build --release isn't that hard of a command to run
