### ISSUE TITLE
Some Perks Apply to Everyone

### ISSUE THREAD

**Issue by apeckdev** [IntQuant/noita_entangled_worlds#19]
There seems to be a few perks that will apply to both the Host/Client if only one player takes them. So far I've noticed:
- Gold is forever
- Perk Lottery

It seems like anything that doesn't directly affect the player will essentially be a free perk for the other players. This might be nearly impossible to fix when thinking about perks like exploding corpses - perhaps a fair workaround would be to only enable these perks if all players take them.

**Comment by Weightychip123** [comment]
Im pretty sure Gamble is also one of these perks

**Comment by IntQuant** [comment]
One way to solve it would be to only let host pick perks for everyone, but it's a somewhat boring way to do it so I'd like to avoid it. (Maybe make it an options tho)

Some could be just not synced to other players (Like Gamble and Perk Lottery). Some could have less effect depending on player count (The health increase one, more love/hate, more blood and others)

The on/off perks... Maybe they could work on random chance, depending on percentage of players that picked them?

Then there is Glass Cannon, which limits max health to 50... yeah I'm not sure what to do about it.

**Comment by RaskiTech** [comment]
For glass cannon: How about keep the upside and change the downside so that the player with it takes 5x more damage. Alternetively, you could also calculate the new damage the player takes with oldDamage * (health / 50) and that would be similar to the normal one. These effects would of course only be on the person with the perk.

**Comment by IntQuant** [comment]
Yeah that could work.

**Comment by IntQuant** [comment]
We have #116 now, that goes more in-depth on what perks are broken exactly, so this can be closed.
