### ISSUE TITLE
Dead mina throws all flasks 

### ISSUE THREAD

**Issue by SollyBunny** [IntQuant/noita_entangled_worlds#193]
Its slightly annoying when you have ambrosia and instead of pouring it on themselves, the dead mina decided to throw it... then also throws every other flask.

Can there be a toggle to disable allowing throwing flasks

**Comment by bgkillas** [comment]
he would actually be harder if i made him pour it, but yeah i have been considering options to lessen that, maybe eventually

**Comment by bgkillas** [comment]
i think i disagree, you can modify him to not if you really dont like it
