### ISSUE TITLE
When host dies and others disconnect, noita doesn't let you continue even if you save and quit

### ISSUE THREAD

**Issue by SollyBunny** [IntQuant/noita_entangled_worlds#194]
When host dies and others disconnect, noita doesn't let you continue even if you save and quit

**Comment by bgkillas** [comment]
you saved and exited then restarted the proxy while the host was dead?

**Comment by SollyBunny** [comment]
> you saved and exited then restarted the proxy while the host was dead?

yes, noita doesn't give the option to continue
