### ISSUE TITLE
These are the bugs i found on latest

### ISSUE THREAD

**Issue by viljoOlen** [IntQuant/noita_entangled_worlds#196]
1. Everything resets in proxy when i open it always it askes the nouta exe the mods and the language too
2. The skin of host is default noita even if he haves crown or amulet or Colored it
3. Other players crown cant be seen or amulets

**Comment by bgkillas** [comment]
are you playing ip connect? i cant replicate any of these lol

**Comment by viljoOlen** [comment]
Well no we are playing whit the host copyboard thingy

**Comment by niraethm** [comment]
Not sure how to reproduce it but using Steam connect (using the lobby id) is how I've been connecting and friends have been connecting with me using the same method.

Both my friend and I are using the Linux executable for reference.
