### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by VELTR0** [IntQuant/noita_entangled_worlds#2]
Maybe I make a mistake somewhere else but just to be sure: The IP address for joining is supposed to be the global IP4 address of the host, right? The one you get when you enter https://www.whatismyip.com/

**Comment by IntQuant** [comment]
That probably means that you're behind a NAT, and your ip address is shared by several users. 

[Here is how you can check that](https://superuser.com/questions/1399853/double-nat-how-can-it-be-detected-and-why-how-it-should-create-issues)

You might want to try one of virtual network solutions, like hamachi/tungle/openvpn.

**Comment by VELTR0** [comment]
So local IP adresses also should work (especially when both are in the actual same network)?

**Comment by IntQuant** [comment]
Yes, local IP address should work in same network.

**Comment by IntQuant** [comment]
You can also try steam networking, which is supported in v0.2, now.

**Comment by VELTR0** [comment]
Steam networking lets us connect in the console but we can't see each other ingame. There is also no ingame message. Does the mod need to ba activated in the in game menu? We're on the same Noita branch and no other mods.

**Comment by IntQuant** [comment]
Yes, the mod needs to be activated in the "Mods" menu.

**Comment by VELTR0** [comment]
Well, activating the mod fixed it. 
I just stupidly followed the install instructions without thinking of this simple thing
