### ISSUE TITLE
Holy Mountain Collapse is not Synced

### ISSUE THREAD

**Issue by apeckdev** [IntQuant/noita_entangled_worlds#20]
Each player seems to have their own instance of the holy mountain collapsing. I noticed as the client that if the host leaves before I do I can still use the wand tinkering altar but I will start to suffocate inside of invisible terrain. Ideally, if one player triggers the collapse it'll trigger it for all players.

**Comment by 1DarkLight1** [comment]
To correct you: as far as I noticed, only the HOST'S collapse matters actually. Yes you get blocked by collapse mountain's debris on your end, but you are still able to tinker with your wands for some reason. When the host breaks their mountain, however, you both suffocate & are unable to tinker with the wands, even if your own mountain never got collapsed.

**Comment by IntQuant** [comment]
Currently (v0.12.6) only local collapse matters for wand tinkering. There were several versions of the mod where any player could trigger a collapse for everyone, but that felt kinda bad so I'm leaving it as-is.
