### ISSUE TITLE
Multi-player should be an unlockable spell , maybe a small quest ^^

### ISSUE THREAD

**Issue by jonnytest1** [IntQuant/noita_entangled_worlds#200]
As the title says I think it'd be neat to make the multi-player aspect a spell that can be unlocked in game ,
I'm thinking one version where u do multi-player from start without unlock and another version where multi-player is a spell similar to dark souls summoning 👀

**Comment by IntQuant** [comment]
That would require remaking quite a bit of core code, so very unlikely to happen.
