### ISSUE TITLE
Perform hue shifts in OKLCH space instead of HSV

### ISSUE THREAD

**Issue by BlueAmulet** [IntQuant/noita_entangled_worlds#206]
HSL/HSV colorspaces have poor correspondence to human color perception and a lot of the resulting hue shifts also appear to change the color's brightness and saturation. OKLCH is a colorspace that take into account human color perception and can be used to generate hue shifted colors that are the same saturation and brightness as the original color.

![combine2](https://github.com/user-attachments/assets/944bd259-6ea3-494d-94f6-c7f85049718f)

Here is an example of this, a hue shift of 260. In HSV the image has overall desaturated and the cape has gotten brighter, while OKLCH has preserved the saturation and brightness of the colors.

**Comment by bgkillas** [comment]
would you mind implementing this? relavent code to change https://github.com/IntQuant/noita_entangled_worlds/blob/master/noita-proxy/src/player_cosmetics.rs#L115 i have just spent alot of time being annoyed at colors before this project so im lazy

**Comment by bgkillas** [comment]
actually i will implement this

**Comment by bgkillas** [comment]
wow, just tried the old slider again and this looks so much more consistent, very cool
