### ISSUE TITLE
Mod failing to initialise despite vcredist 2022 being installed [proton/linux]

### ISSUE THREAD

**Issue by alicealysia** [IntQuant/noita_entangled_worlds#209]
As per the FAQ I installed the latest supported vcredist.
I did this via protontricks then via the downloadable exe from microsoft to ensure that I didn't miss anything. When this didn't work I added every dll to my dll overrides.

it says it can't find noitapatcher.dll, however this file is present in the relative directory it points to.

Did I install vcredist wrong? is something else going on?

![image](https://github.com/user-attachments/assets/2c8b87fc-16a5-4ce8-b5f3-3e326f5a7994)

Folder in question

![image](https://github.com/user-attachments/assets/59a7481c-92eb-448f-aa47-d867a5972672)

**Comment by alicealysia** [comment]
cool, uninstalling all the reddists and installing from file worked.
basically, linux users need to:

1. install protontricks if not already present
2. download the vcredist 2022
3. open vcredist 2022 installer via protontricks (note, best to run this in an x11 window manager, xwayland-satellite hates this)

should now work.

be careful not to install the VCRedist via the protontricks dll installer or you'll cause yourself a great deal of pain

**Comment by IntQuant** [comment]
Have you installed x86 version of vcredist? https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
