### ISSUE TITLE
Crashed in second left parallel world holy mountain

### ISSUE THREAD

**Issue by RedstoneFX** [IntQuant/noita_entangled_worlds#212]
The three of us were playing. Having reached a more or less developed state, we moved to parallel worlds for additional perks. The first parallel world did not cause any problems for any of us, but in the second, one of us began to experience crashes (the holy mountain after the jungle). Now the crash occurs almost immediately after logging in (up to 5 seconds). It is noteworthy that the remaining two players do not experience similar problems at all. We were able to extract some logs via noita_dev.exe However, it turned out to be the maximum we were capable of...
[Latest.txt](https://github.com/user-attachments/files/17689123/Latest.txt)
We also used three additional mods:
- Sellhole
- Disable Auto Pickup of Collectibles
- Advanced Spell Inventory (seems to work properly)

**Comment by IntQuant** [comment]
Do you still have the save?

**Comment by RedstoneFX** [comment]
Yes! Here's everything you might need to reproduce this crash.
[Saves](https://www.dropbox.com/scl/fi/tatcyhdqkctict728ncob/EverythingForCrash.zip?rlkey=04xjf5d3wu7zk1hnuukrrxy3d&st=ub13bqut&dl=0)

**Comment by IntQuant** [comment]
Thanks for providing the save. You could try to recover the save by deleting world/entities_27789.bin in crashing player's save.
