### ISSUE TITLE
error 10054 gane crashing to the client in like 1 minute of playing or going down, also some lag

### ISSUE THREAD

**Issue by Uvathar** [IntQuant/noita_entangled_worlds#214]
![image](https://github.com/user-attachments/assets/8744f48f-43c3-42ef-8e71-17d6378279d0)

Im having a problem where we can connect and see each other perfectly and play but we enter the cave or pass a minute or so and the game for the client player crashes, but still in lobby and can rejoin but still crash

**Comment by thekmodo** [comment]
Came to see if this was reported, my friend and I just installed v0.28.3 patch release and are experiencing the same issue

**Comment by IntQuant** [comment]
Know issue with v0.28.3

**Comment by IntQuant** [comment]
Yes

**Comment by IntQuant** [comment]
Fixed in v0.28.4

**Comment by Uvathar** [comment]
YESS thx
