### ISSUE TITLE
[request] gold-share

### ISSUE THREAD

**Issue by sndrec** [IntQuant/noita_entangled_worlds#217]
my number one hot feature request for entangled worlds is some manner of gold-share, so players aren't obligated to stay on each other's asses to collect the gold from their kills. being able to go our separate ways would make the mod feel a lot more freeing!

whether that's gold being equally split between players upon pickup or some way to drop or send your gold to other players, as long as it's possible to spread the wealth.

**Comment by bgkillas** [comment]
we would also need to reduce the incomming gold by 1/N but yeah sounds doable
