### ISSUE TITLE
[Request] Options for player death and respawning

### ISSUE THREAD

**Issue by Perryplats** [IntQuant/noita_entangled_worlds#222]
Options like setting the health and damage of a dead players phantom, how much players re-spawn with, and alternate respawn options other than killing the phantom (such as entering a holy mountain)

**Comment by bgkillas** [comment]
last bit will exist sometime, others i disagree with

**Comment by ChooMcoo** [comment]
Please, this would be appreciated so much. I and the folks I play with are by no means good at the game, and would appreciate an alternative respawn mechanic such as reaching the next Holy Mountain

**Comment by bgkillas** [comment]
lazily done in next release
