### ISSUE TITLE
Lobby text too tiny

### ISSUE THREAD

**Issue by gumshrew** [IntQuant/noita_entangled_worlds#223]
Issue is on steam deck with and without external monitor. The installer prompts were too tiny to read, used a magnifying glass to get thru them and install successfully. All text in the lobby/game settings is also too tiny to read. Is this a known issue with an easy fix?

**Comment by IntQuant** [comment]
The main issue is that I can't test it on a steam deck because I don't have one. There is a `--ui_zoom_factor (number)` command line argument that can set ui size that is set to 0.3 on steam deck by default, you could try a different value.

**Comment by gumshrew** [comment]
Is there any other prompts I need to set that value specifically to the EntangledWorlds mod?

**Comment by reesque** [comment]
The arg works for me :+1:
