### ISSUE TITLE
Version Error: (404 Not Found) for url (<...>/v0.30.6)

### ISSUE THREAD

**Issue by mobergmann** [IntQuant/noita_entangled_worlds#232]
When running the proxy I get the error message:
```
Encountered an error: 
 Failed to download mod

Caused by:
   0: while getting release for tag Tag("v0.30.6")
   1: Failed to get release by tag from https://api.github.com/repos/IntQuant/noita_entangled_worlds/releases/tags/v0.30.6: response returned an error
   2: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/IntQuant/noita_entangled_worlds/releases/tags/v0.30.6)

Location:
    src/bookkeeping/releases.rs:234:48
```

I have the latest Game version
![image](https://github.com/user-attachments/assets/bc60958d-db1a-4316-b7b4-f8496e96727d)

I am on nixos, to run the program I compiled the proxy myself.

**Comment by mobergmann** [comment]
Apparently the latest commit (8d40e2f0f9b2330869de5387517ce1f78dc621b8) caused the error. I don't know why the version was bumped, when there is no new release, but I suggest either reverting the change or uploading the newest release. At least for me, reverting the change fixed the issue. 

PS: Based on the commit message, it seems, that the commit was automated. Maybe the usage of GitHub actions, to compile the proxy and automatically release the binary could prevent this type of error in the future.

**Comment by mobergmann** [comment]
I can't use the binaries, because I am on NixOS. To run executable, you either have to search a package, package the software yourself, or compile the executable yourself. I tries to package it myself, without much luck, because of many wayland issues and therefore resorted to building it myself.

**Comment by bgkillas** [comment]
yeah but doesn't mean you have to build from master

**Comment by ValdemarGr** [comment]
@mobergmann 

I also use nix. I created a flake [here](https://github.com/ValdemarGr/noita_entagled_flake). 

I launch it like this
```bash
launch_noita_srv /nix/store/sqhxm5i51nfqsr9qfim4gw43gy6k17mq-source/proton
```

![image](https://github.com/user-attachments/assets/c2de4619-e6bf-4494-8cc4-d73149899f13)

### Explanation
The binary produced requires some patching to work. If I try to make it an FHS emulated env, gpu drivers justifiably fail to load when the application in the FHS environment tries to launch the game. The default launch command tries to run steam's `_v2-entry-point` program to launch the application inside of the "steam container" that the proxy program starts, which it wants to do to connect with the steamworks client? Anyhow, there's some funky patching going on with nixpkgs' steam wrapper, so it's easiest just to run the whole launcher command with nixos' steam-run command which will handle all of the dependencies.
