### ISSUE TITLE
Client cant drop Item, Spells, Wands

### ISSUE THREAD

**Issue by lkaesberg** [IntQuant/noita_entangled_worlds#234]
Hello I really love the project and never thought this would be possible to add true multiplayer to noita. But this is really cool.

Since one of the newer version I sometimes get this error when dropping a wand, spell or item. It doesnt always happen but only for the client. The server cant see the item.
![20241127145957_1](https://github.com/user-attachments/assets/674a8561-cef7-460a-a1c5-66df343c49ae)

**Comment by bgkillas** [comment]
i got lazy and reuploaded quant.ew shortly after release, remove mod from mods folder next to noita.exe and open proxy again
