### ISSUE TITLE
Sniper lasers only visible to host

### ISSUE THREAD

**Issue by Haydoggo** [IntQuant/noita_entangled_worlds#240]
Version 0.30.7
Only the host is able to see the laser pointers of the snipers and rocket tanks in the Snowy Depths

**Comment by HaecEsneLegas** [comment]
If not fixable via Lua context.. is it possible to just render a line as a constant based on the angle the sniper is looking. If we can't get it to show "correctly" at least seeing a line at all would allow players to anticipate the sniper.
