### ISSUE TITLE
my microsoft defender found a "Trojan:Win32/Wacatac.B!ml" in " C:\Users\\Downloads\noita-proxy-win\noita_proxy.exe"

### ISSUE THREAD

**Issue by xyroxz** [IntQuant/noita_entangled_worlds#245]
yeha thats pretty mutch my issue

**Comment by StoredMink** [comment]
hmm, have same issue too, But I don't remember this earlier.

**Comment by 0x4B495454** [comment]
I have the same issue.

**Comment by Eduardo-Bender** [comment]
I have the same issue aswell, also v0.30.09 seems very unstable, kept having connection problems, went back for the 0.30.07 to play today

**Comment by RudyKolibri** [comment]
same here the switching to 30.07 is currently fine

**Comment by lintglitch** [comment]
Similar issue with Avira

**Comment by bgkillas** [comment]
closing since #251 is more meaningful issue
