### ISSUE TITLE
Possible bug when non-host player selects New Game

### ISSUE THREAD

**Issue by GACGAMA** [IntQuant/noita_entangled_worlds#246]
Hi!
I've been playing with my brother and we got into a god run
I'm the host, and he's entering the room by opening the gaming and selecting new game.
This has worked, but today something different happened
His wand caused his game to crash.  Upon reentering, he selected new game (as usual), but his save got reseted and he lost all progress. When I tried recreating the room, my character got bugged (Resetted, but still holding the old wand, but that did not fire)
I had a backup save, when I backed-up my save, I got everything back  but my brother got his character reseted.

I'm not entirely sure what happened

**Comment by bgkillas** [comment]
new game starts a new game like in vanilla, continue continues the game like in vanilla, crashes may be our problem but rest is expected
