### ISSUE TITLE
Additional to nixpkgs or add flake?

### ISSUE THREAD

**Issue by FBIGlowie** [IntQuant/noita_entangled_worlds#249]
Hello, are there plans to get a way to run this "natively" on NixOS for like the 2 NixOS users out here? Either via a flake module or addition to nixpkgs?

If not, would y'all welcome a pr to do that?

**Comment by IntQuant** [comment]
A pull request would be nice, as I assume that Nix user would know better how to configure that properly.

**Comment by ValdemarGr** [comment]
I have already made a flake if you can use that as a starting point.

https://github.com/IntQuant/noita_entangled_worlds/issues/232#issuecomment-2510341779

**Comment by FBIGlowie** [comment]
> I have already made a flake if you need a starting point.
> 
> [#232 (comment)](https://github.com/IntQuant/noita_entangled_worlds/issues/232#issuecomment-2510341779)

Thank you thank you

**Comment by ValdemarGr** [comment]
> > I have already made a flake if you need a starting point.
> > [#232 (comment)](https://github.com/IntQuant/noita_entangled_worlds/issues/232#issuecomment-2510341779)
> 
> Thank you thank you

I think for most setups you can just use the `steam-run` command that emulates a lot of FHS things.
`https://www.youtube.com/watch?v=HJHgls38ePA`

**Comment by ValdemarGr** [comment]
> > I have already made a flake if you need a starting point.
> > [#232 (comment)](https://github.com/IntQuant/noita_entangled_worlds/issues/232#issuecomment-2510341779)
> 
> Thank you thank you

I think for most setups you can just use the `steam-run` command that emulates a lot of FHS things.
``

**Comment by FBIGlowie** [comment]
> I think for most setups you can just use the `steam-run` command that nixpkgs' steam package comes with which emulates a FHS env with most if not all necessary dependencies. `steam-run ./noita_proxy.x86_64`

yea this is how I originally used to do it, idea came up because I wanted to use `nix run` and immediately hop in.
I think your flake does have some fhs stuff which I will experiment with!

**Comment by ValdemarGr** [comment]
This is the issue I ran into when letting `noita_proxy` launch the game outside of `steam-run`, but wrapped in a FHS env. The error seems to be driver related.
```
2024-12-02T00:43:29.835413Z  INFO noita_proxy::bookkeeping::noita_launcher: Game path: /home/valde/.local/share/Steam/steamapps/common/No
ita
/nix/store/6xd7halb89mlp2c44i6pb5hpmhi5d135-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: undefined symbol: g_assertion_message_c
mpint
Failed to load module: /nix/store/6xd7halb89mlp2c44i6pb5hpmhi5d135-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
fsync: up and running.
Setting breakpad minidump AppID = 881100
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198052209451 [API loaded no]
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  284
  Current serial number in output stream:  283
```

I think it omitting `steam-run` might cause a lot of the issues that `steam-run` fixes. I think including `steam-run` into the launch command might be the better solution.

**Comment by FBIGlowie** [comment]
Ok ok, I feel like the flake just will be a fetchzip to a wrapper bash script that basically is `steam-run noitaproxy`and then a actions workflow to update the version and hash per release.

That's where I got to last night experimenting.

**Comment by ValdemarGr** [comment]
It definitely sounds like the simplest solution.

Does the proxy ship with non-steam support (GoG)? I seem to recall seeing a flag in the GUI, but I am unsure of the implications?

**Comment by FBIGlowie** [comment]
i am almost done

**Comment by FBIGlowie** [comment]
So it's steam run with latest + adding update upon release workflow rn
