### ISSUE TITLE
Mobs disappearing, spells flashing and weird errors appearing

### ISSUE THREAD

**Issue by Bogfox** [IntQuant/noita_entangled_worlds#253]
V0.30.10

There were some weird stuff happening when me and 2 other players were playing through steam. At start, sometimes we would see that when a certain player joined (could be any one of us) weird error messages would appear. Interesting thing here is that when that certain player would pickup the perk "Electricity", everytime the player "produced electricity", the error message repeated itself.
This was the text:
![Screenshot 2024-12-03 220051](https://github.com/user-attachments/assets/aaaf4ac3-63f8-424c-b2e3-237ad0ffa21f)

There were also issues with spells, mobs and wands disappearing and sometimes showing themselves only to certain players and sometimes the map didn't load in properly. We tried restarting and launching the game (and proxy) many times but the issue persisted and we double checked we had same versions and stuff.

**Comment by bgkillas** [comment]
prob fixed next version
