### ISSUE TITLE
Auto "end run" when newgame and some physics lagging even when near host

### ISSUE THREAD

**Issue by dekconcat** [IntQuant/noita_entangled_worlds#262]

**Comment by bgkillas** [comment]
what does auto end run mean lol, physics lagging is expected

**Comment by dekconcat** [comment]
Sry for my stupidity. All new run play the same seed till I click on "end run" button

**Comment by kcalbxof** [comment]
> alway turn on "end run" when new-game.

It was expected behaviour pre 0.30, something broke it seems.

**Comment by bgkillas** [comment]
seed not changing on new game? i cant replicate
