### ISSUE TITLE
how can i fixit, tc

### ISSUE THREAD

**Issue by oldsboy** [IntQuant/noita_entangled_worlds#270]

**Comment by oldsboy** [comment]
![微信图片_20241208160501](https://github.com/user-attachments/assets/2e8a690b-af0f-470a-bead-c8e920890ab9)

**Comment by oldsboy** [comment]
it init error

**Comment by IntQuant** [comment]
You may be missing a dependency. Try installing the VC++ redistributables from there: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022. You want the x86 version because Noita is 32 bit and needs 32 bit libs.

**Comment by oldsboy** [comment]
yes! i use some software to install this dependency,and it can be work! thank ! ❤
