### ISSUE TITLE
noita_proxy.exe doesn't launch and it creates ew_log.txt

### ISSUE THREAD

**Issue by Ghilas1009** [IntQuant/noita_entangled_worlds#273]
i tried run as an admin does the same thing
[ew_log.txt](https://github.com/user-attachments/files/18074875/ew_log.txt)
![image](https://github.com/user-attachments/assets/f951d38a-1f1d-42c4-b3a8-8c34acdb63ec)

**Comment by IntQuant** [comment]
Is your gpu older than 13 years?

**Comment by Ghilas1009** [comment]
i just solved the problem im on a laptop and it was launching on the integrated graphics and not in dedicated, i changed it manually in the invidea panel to launch it with dedicated graphics card , works fine now.
