### ISSUE TITLE
Connection Isuue

### ISSUE THREAD

**Issue by Onomatophobic** [IntQuant/noita_entangled_worlds#279]
When me and my friend try to join each other's games (we've tried for both, and ip based) it doesn't work. It gives this message to the one joining.
"An error occurred: lobby does not exist"
But the server and game is running.
"Local Noita instance connected."

**Comment by bgkillas** [comment]
![image](https://github.com/user-attachments/assets/f33f9eec-008e-4d08-86ef-572ecf80f40e)
i hope you both can read this option, reopen if you still have an issue, dont use ip

**Comment by Onomatophobic** [comment]
I had that on, he might not have, but now its saying there was an error launching the mod in the Noita game
