### ISSUE TITLE
Can not control my character after it was resurrected

### ISSUE THREAD

**Issue by GoiDcl** [IntQuant/noita_entangled_worlds#292]
If you select some item in your hotbar while you are dead, then after resurrection there are plenty of lua errors and you can't control a character and you are also invincible. It can happen to either host and to another player.

![13123](https://github.com/user-attachments/assets/19eaac6b-7028-4da3-97fd-3177589f9147)

**Comment by bgkillas** [comment]
nope, hotbar is intentional and unrelated, cant replicate

**Comment by GoiDcl** [comment]
> nope, hotbar is intentional and unrelated, cant replicate

Okay, i will close for now, because this didn't happen recently. Last time i had this problem was on version 32.6 and on local network. We updated to 32.7 and now are playing from different locations, seems good

**Comment by 3RepresentsTheory** [comment]
The issue still persists in version 0.32.7, with numerous Lua errors occurring and players becoming invincible.

**Comment by bgkillas** [comment]
maybe fixed in next update still have 0 idea what causes it but whatever
