### ISSUE TITLE
Customize Players' Names

### ISSUE THREAD

**Issue by 3RepresentsTheory** [IntQuant/noita_entangled_worlds#293]
Currently the proxy displays users' names based on their Steam names. However, if a Steam name contains non-ascii characters like Chinese, it appears as a series of '????' symbols, which not only are lengthy but also obstruct the view. I was wondering if it could be possible to implement a feature that allows for the customization of players' names.

**Comment by IntQuant** [comment]
![Screenshot_2024-12-21_11-29-31](https://github.com/user-attachments/assets/47edbff7-1f29-46de-8aa1-e0294b44a244)

**Comment by 3RepresentsTheory** [comment]
thank you!
