### ISSUE TITLE
Crystal Key does not work. *SPOILERS*

### ISSUE THREAD

**Issue by MyUsernamee** [IntQuant/noita_entangled_worlds#298]
If you get the crystal key from the Alchemist and attempt to give it a voice by kicking the music machines it doesn't do anything.

## Steps to reproduce
1. Kill the alchemist boss.
2. Get crystal key.
3. Kick music machine.

## Expected result
There should be a message saying the key listens and then you can use it to complete some quests.

Thank you for your time, and I tried to format this the best I can, and provide as much information as I can. :skull:

Again thank you. This is truly one of the greatest mods for this game. Me and my friends have literally put in a couple hundred hours with mod.

**Comment by bgkillas** [comment]
at least you tried to make it reproducible, unfortunately, cant reproduce

**Comment by IntQuant** [comment]
Did you drop the key first?

**Comment by MyUsernamee** [comment]
I'm going to be honest, no... :laughing: Sorry for the unnecessary issue, truly a skill issue on my part.
