### ISSUE TITLE
client-side player's game started behaving strangly after entering the last holy mountain

### ISSUE THREAD

**Issue by kitspin** [IntQuant/noita_entangled_worlds#30]
we made it through an entire run with no major issues besides a few chunks unloading now and then, but for some reason when we entered the laboratory the client-side player (game was just me and them) suddenly started receiving every perk in the game one at a time every second. i have no idea what caused this, but it seemed to start directly after they entered the final portal.

![image](https://github.com/IntQuant/noita_entangled_worlds/assets/159738142/ef529011-2287-4892-bf50-794b9a2d5e64)

after this happened we rushed over to kolmi to try and beat the game before anything else happened. freeze field caught my friend in their acid-trail and they started to take constant damage, which caused them to rapidly cause giant explosions because of glass canon + revenge explosion. 

they are new to noita and had never even gotten to the jungle before this run.

edit: forgot to mention, after this run we stopped playing and when i tried to open noita again later it would crash every time. deleting the mod fixed it.

**Comment by IntQuant** [comment]
Yeah this is very weird, especially the crash at the end.

**Comment by IntQuant** [comment]
Kolmi issues were fixed, will be released in v0.14
