### ISSUE TITLE
[0.7.0] Could not init websocket: Interrupted handshake (WouldBlock)

### ISSUE THREAD

**Issue by khonkhortisan** [IntQuant/noita_entangled_worlds#39]
- 💻3 computers connected via an ethernet switch
- 📁192.168.1.1 shares a network folder with the game in it
- ❌ the host fails to connect to itself with the error `Could not init websocket: Interrupted handshake (WouldBlock)`
- ⬛ 192.168.1.2 host black screen, 🐛 192.168.1.3 guest bugfree screen
- 🐛 192.168.1.3 host bugfree screen, ⚡ 192.168.1.2 guest connects with +25k $99k that immediately changes to +25k $100k. Picking up the heart on the left changes the health to 25025.
- the guest has to newgame before the host, or it gets the same error. Sometimes it gets the error anyway.
- On 0.2.0 I was once able to get 192.168.1.1 and 192.168.2.3 connected right at the beginning, then one disconnected.
- 🤼 I've played using M-Néé+Kappa (p2 meat shield+infinite wands+slow+immunity), and with Noita Together (weak player dies early, have to decide between killing p2 for multiplayer restart, or p1 gives up and p2 continues in singleplayer), but have yet to play one game with this mod.
- ♨ 192.168.1.2 Steam networking Could not init steam networking: We cannot connect to Steam, steam probably isn't running
- ♨ 192.168.1.3 Steam networking Could not init steam networking: Some other failure
- 🔧 no other mods enabled
- 🐌 singleplayer performance: 192.168.1.2 has slow movement the whole game, 192.168.1.3 has freezes
- 🛜 if anything accesses the internet, it goes through a pdanet mobile hotspot
- 📶the computers can ping each other without packet loss
host 192.168.1.3 when guest connects first:
![Capture](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/5e0cd805-fbb9-4782-ae5b-96f292edd73a)
![Capture2host](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/bd6e52cc-ac89-4834-8ba2-7a6285c4b0da)
guest 192.168.1.2:
…and now I can't connect as guest to screenshot the health bar, even by restarting all 4 parts. So here's guest failing to connect multiple times without closing its noita-proxy
![imagen](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/afcc527d-5cb5-43fe-b7c9-8c16ba8786a8)
![imagen](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/ed7c9f56-3ac9-4b1a-a621-0d2bf6bd871e)

**Comment by IntQuant** [comment]
- You probably have debug mode on. It gives 25k health, gold, and several starting perks
![image](https://github.com/IntQuant/noita_entangled_worlds/assets/25219447/a361afe6-cb86-4655-883c-f0ab9bab38e3)

 - "Can't init websocket" is somewhat new. I'll try to fix it in the next version.

**Comment by khonkhortisan** [comment]
[0.8.0] We can connect, see each other's movement / mouse pointers / shots, then it desyncs fairly quickly (with us just standing there, or around when we kick the minecart). The other player's movement lags behind, then stops completely.
guest: Error while broadcasting message of len 141: Message dropped
host: Peer 1 removed
![peer1removedguest](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/4bf05e48-1dbd-41c1-8681-0a73967ca70a)
![peer1removed](https://github.com/IntQuant/noita_entangled_worlds/assets/1996449/e0ad3548-47a6-46ca-b6e8-85e827d04820)

**Comment by IntQuant** [comment]
Try connecting by steam, connection by ip isn't that good and hasn't been worked on since v0.1.

**Comment by khonkhortisan** [comment]
🔌removing the switch and directly connecting ethernet doesn't stop it from desyncing
Yes, steam networking works
