### ISSUE TITLE
No way to restore progress if player leaves/crashes midgame

### ISSUE THREAD

**Issue by Ydrec** [IntQuant/noita_entangled_worlds#40]
When rejoining after a crash you always start at the entrance to mountain.  Using Continue or restore autosave buttons just hangs the game with black screen. Connecting using new game button does work but player loses all their items/perks/wands, starts at the top of mountain and all pickups respawn like hearts and perks in every holy mountain.

**Comment by IntQuant** [comment]
Continue *should* work. Do you still have proxy running?

**Comment by Ydrec** [comment]
@IntQuant After game closes/crashes you cant start noita because noita is still running according to steam because of proxy. To be honest i have not tried running noita.exe directly from game folder. If you close proxy then open noita, then click restore autosave or continue, game hangs indefinitely.

**Comment by Ydrec** [comment]
Using noita.exe continue button works as host with empty lobby, sudden game closing or save and quit doesnt break it, starting game after restarting proxy also works. Going to do some testing with people in lobby

**Comment by Ydrec** [comment]
Tested with actual people, continue button works if you dont close proxy.

**Comment by SollyBunny** [comment]
Using steam, we have disconnected twice, both times we both see only ourselves in the server

**Comment by IntQuant** [comment]
Just restart the proxy and continue the game
