### ISSUE TITLE
Mod might be setting single_threaded_loading to 1 when used and not cleaning up

### ISSUE THREAD

**Issue by Ydrec** [IntQuant/noita_entangled_worlds#44]
After a few sessions people reported that game loading behaved differently (long black screen and short logos as opposed to logos for entire loading screen). It was pinpointed to single_threaded_loading being set to 1 in \Nolla_Games_Noita\save_shared\config.xml. By default on fresh install that value is 0.

**Comment by IntQuant** [comment]
Hmm, the mod doesn't touch that file. It that the game setting it after a crash?

**Comment by Ydrec** [comment]
After a few tests yes, if you fail to load a world for a while noita would go single thread. So not a problem with a mod. 
![изображение](https://github.com/IntQuant/noita_entangled_worlds/assets/53411693/28209373-d2a7-4e22-bd2b-fb51eb7cbbf7)
