### ISSUE TITLE
Client seeing phantom enemies around the game

### ISSUE THREAD

**Issue by cockchamp47** [IntQuant/noita_entangled_worlds#45]
Several of the spider-type enemies in the jungle and surrounding areas create phantoms for the client. There are enemies that do not take nor deal damage, but do block projectiles. 

Notably, this also seems to happen with Taikasauva and Kummitus (noita ghost) as well.

We are playing with V1 world sync (been working beautifully btw with the last few updates!!!)

**Comment by IntQuant** [comment]
Has been fixed at some point.
