### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by clragon** [IntQuant/noita_entangled_worlds#47]
A windows installer executable would be nice. 

Preferrably, it would install the proxy in the folder for programs and add a shortcut to the start menu.
There are various programs that can aid in this endevaour, for example, [InnoSetup](https://jrsoftware.org/isinfo.php) or [NSIS](https://nsis.sourceforge.io/Main_Page)

**Comment by clragon** [comment]
Many applications that do not wish to invoke admin privileges for installation and updates choose to be installed in `%APPDATA%` instead. We can follow this same procedure.

**Comment by Szmaka** [comment]
An auto-updater would be very nice
