### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by stefnotch** [IntQuant/noita_entangled_worlds#55]
I'd love to see slightly longer installation instructions. Maybe even in the Readme file, or in another file that the Readme links to?

Since writing stuff is a chore, I figured I'd write up one possible option:

## Installation

Go to [releases](https://github.com/IntQuant/noita_entangled_worlds/releases) and download the latest `noita-proxy-win.zip` or `noita-proxy-linux.zip`, depending on your OS.

Unpack it, and launch the proxy. Proxy is able to download and install the mod automatically.

![image](https://github.com/IntQuant/noita_entangled_worlds/assets/10220080/33fe542b-ca6b-446f-b988-6d1bcb54f521)

Then, start Noita, and enable the mod.
1. In the "Mods" menu, enable unsafe mods
2. Then, enable the "Quant's Entangled Worlds" mod.

![image](https://github.com/IntQuant/noita_entangled_worlds/assets/10220080/3a45f0ad-2ef1-4896-805c-1c1266e039c4)

Now you're ready to start a server and have fun!

## Connect using Steam

In the Proxy window, click on "Create Lobby". Then, "Save lobby ID to clipboard". Send that ID to your friends, who can then *copy* it and press "Connect to lobby in clipboard".

![image](https://github.com/IntQuant/noita_entangled_worlds/assets/10220080/fc3c1ee7-6853-4783-8134-8bcaccc57d8e)

After that, just start a new Noita game on everyone's PCs, and you should be in multiplayer mode :)

**Comment by stefnotch** [comment]
Also, thank you and everyone involved so much for this absolute masterpiece of a mod. This is a dream come true for me. <3

**Comment by IntQuant** [comment]
Thanks for providing detailed installation instructions, I've added them to readme.
