### ISSUE TITLE
Visual desync with players burning

### ISSUE THREAD

**Issue by RaskiTech** [IntQuant/noita_entangled_worlds#57]
Hey, I tried this mod out with a friend and it was really cool. However, because neither of us have barely any noita experience we were constantly burning and struggling. There was often a really noticeble visual bug where the other player would appear burning. Of course not a huge deal, but it would be nice to also sync up being on fire

**Comment by RaskiTech** [comment]
Really easy but a bit hacky way would be to just check if there is any incoming fire damage and extinguish the player if not and/or only put them on fire if they receive fire damage. Really just depending on what is easiest with the noita engine

**Comment by bgkillas** [comment]
mostly fixed
