### ISSUE TITLE
Ambrosia synchronization

### ISSUE THREAD

**Issue by Steanky** [IntQuant/noita_entangled_worlds#58]
Sometimes when a client is stained with ambrosia, "invisible" damage can still be dealt to them. For the client, the red damage pop-up doesn't appear. For the host, the damage pop-up appears. The health bar is going down for both.

This happens either when a client has an active ambrosia stain, or specifically when a client is sitting in pool of ambrosia that doesn't exist on host's game. I'm not sure which.

This happened while using world sync V1.

Steps to reproduce:

- Client gets stained with ambrosia
- Client gets attacked by an enemy (we specifically tested using melee damage but other types may work too)
- Notice that the enemy's attacks still damage the host even though the client should be immune from the ambrosia

**Comment by IntQuant** [comment]
Melee damage is kinda handled on client now. Thus melee damage should work with ambrosia.
