### ISSUE TITLE
Setup Instructions?

### ISSUE THREAD

**Issue by nmurphy101** [IntQuant/noita_entangled_worlds#6]
Just looking for some more detailed instructions for setting this up

I don't see any information about what ports would need to be forwarded for other players to connect.

Seems like it runs on port 58202?

**Comment by IntQuant** [comment]
Noita proxy should run on port 5123, with UDP protocol, which is the only port that should be forwarded. It also has a websocket server running on localhost:21251, used for noita to connect to it.

**Comment by nmurphy101** [comment]
What might be the instructions for running the proxy on linux?

**Comment by IntQuant** [comment]
It should work basically the same way as the windows version. Assuming you are using v0.2, unpack `noita-proxy-linux-v0.2.zip` somewhere and start `noita-proxy.x86_64`

**Comment by IntQuant** [comment]
I guess this can be closed?
