### ISSUE TITLE
Client cannot see electricity boxes

### ISSUE THREAD

**Issue by Weightychip123** [IntQuant/noita_entangled_worlds#7]
Maybe its just randomly happening but so far from what I have played consistently there will be one and the client wont see it on their screen leading to instant death.

**Comment by IntQuant** [comment]
Thanks for the issue! Those things aren't actually synced, I'm just relying on them spawning in the same place on both sides for now. I'll see what can be done about that.

**Comment by Dominig12** [comment]
Here we can add that sometimes there may or may not be chests, and it doesn’t matter who has it and who doesn’t. What the host may have, the client may not have and vice versa.

Сюда можно дополнить, что так же иногда могут быть а могут и не быть сундуки, при том не важно у кого он есть а у кого есть. Что может быть у хоста может не быть у клиента и наоборот.

@IntQuant

**Comment by bgkillas** [comment]
should be synced now
