### ISSUE TITLE
Implement non-shared health as an option

### ISSUE THREAD

**Issue by jah2488** [IntQuant/noita_entangled_worlds#82]
## Problem

When playing with multiple players, a run will most often end when one player mistakenly gets into a bad situation and is dealt more damage than they expected to receive, which instantly kills all other connected players.

This leads to more frustration and finger pointing than the usual bewildered laughter of a gameover in Noita. Combining this with some of the expected and understandable bugs present in a multiplayer mod, leads to a situation where the most "correct" way to play is to be ultra-conservative and to enforce that socially.

## Proposed Solutions
I am pretty sure there is a reason the health system is implemented the way it is currently, so I don't expect any alternative approaches to be "easier" by comparison, but they should improve the feel of playing.

With, nearly, all of these approaches, the idea would be if all players have died, the run is still over as it is currently.

### Team Revive Approach
If a player's HP reaches zero, they "die" and are left on the gameover screen (or some facsimile of it), until one of the other alive players interacts with where they died. The dead player is revived with some portion of their max health restored.

### Auto-Revive at Heart Location Approach
After a player as "died", they simply "spectate" (something) until one of the alive players reaches a heart healing items, at which time the previously dead player is teleported to that location with some amount of their health restored. (Probably without all their wands and items)

### Checkpoint(s) Approach
After a player has died, all of their inventory, items, and spells, are dropped onto the ground where they died and they are teleported back to the last magic mountain or important location that they passed through at some diminished health %.

### 5-Minute Rewind Approach
This approach is more of a way to get around the frustration when dying due to a weird bug or desyncing issue, than changing how the game works currently.

Upon death, present the players with an option to step back in time to the last autosave. This would probably require more frequent autosaving or trigging saves manually within the mod as specific times.

---
I've thought about prototyping some of these solutions on my own, but I figured before I start any of that, I'd get your thoughts on these approaches.

**Comment by Fluup01** [comment]
Ide like the idea of losing all items and respawning at the mountain when someone reaches it. It could possibly make the game too easy, however i do think that everyone having a run ruined because of one player is not fun. However some, including myself, would argue the point of the game isn't difficulty, as i think its a very easy game once you obtain enough knowledge. So the issue of respawning making it too easy is entirely on who you play with. I do think to counteract that you could make all the items they had be permanently gone, however that could also arise the issue of a permanent death loop due to being forced to go deeper for new items without anything on your character. Perhaps that could incentivize teamwork though and force people to play together and protect eachother aswell as share spells and wands.

**Comment by bgkillas** [comment]
in thinking of a fair implementation i think i like the idea of revive at next max hp at half health and stuff but kummitus spawns on your body with the wand you held at death at your point of death, as an attempt to make the problem with your death scale with time

**Comment by IntQuant** [comment]
"Move away" is a bit too much, it should be possible to make them switchable by changing game settings (the ones located in proxy), just like world sync versions can be selected. 

All code related to shared health can be disabled by not loading "damage", "kivi_patch", "patch_meat_biome" systems (see `load_modules()` in `quant.ew/init.lua`)(probably should organize and rename things a bit, given that last two don't make much sense without shared health, but that's not the point). Then a new system would need to be loaded that would handle all that local health stuff.

Now for the game design part.



So a solution consists of several parts: what do we do with dead players, and what do we do with revival.

In terms of what to do with dead players:
I would prefer if dead players always had something to do. I'll mark options that have that quality with (+).
The options are:
 - Just let them wait for revival.
 - Let them spectate.
 - Give them a ghost entity that has to stay really close to a normal player, but can help them in some way (Maybe with a projectile repulsion/deletion field/sector, or give them limited amount of wand slots) (+)
 - Revive them instantly (+)

In terms of what to do with revival:
I would prefer if we stayed close to normal Noita difficulty. It also should still be possible to lose.
Also would prefer if revival would be possible in early game, but still hard in end game.

I personally like approach suggested by @bgkillas. Dying would leave a ghost with whatever wands you had. Then you'd need to kill that ghost either to revive the player, or to just get the items back. Not sure what the lose condition would be in the second case tho.

**Comment by bgkillas** [comment]
my idea was more so just a difficulty thing, i personally think it should only drop the wand you were holding at that time so there is real downsides to dying, but while giving them the wand to at least give the classic noita option of being greedy to try and regain the potentially scary wand. and make so dying could be potentially detrimental to the teammates as your ghost could just murder them.

i think reviving has to be at new/unused holy mountains as revives too fast seem very silly, and just like normal healing in this game via holy mountain hearts, as a way to force you to progress downwards when your in a bad spot. id say wiping everything besides perks and that 1 wand from your ghost would make the most sense, and even letting the ghost you leave behind copy your perks(that would make it real hard late game to get your wand for sure), but i probably like difficulty a bit more then normal (aspecially multiplayer) players.

**Comment by bgkillas** [comment]
oh yeah, kivi/deer boss should scale to all players hp combined total, and likely would have to make them still damage everyone to leave them as scary as deserve to be, i think other bosses/things that i can think of are fine though

**Comment by IntQuant** [comment]
Hi @jah2488 , have you done any prototyping on this yet? I'm going to look at this myself soon-ish.

**Comment by ManiolProgrammist** [comment]
"Dying would leave a ghost with whatever wands you had. Then you'd need to kill that ghost either to revive the player, or to just get the items back. Not sure what the lose condition would be in the second case tho." healing another player should take half of your current hp and give it to him, or pernamently cut health by lets say... 25%? for you both?

Something along these lines, overall, for me seems like amazing idea.

**Comment by bgkillas** [comment]
take 25%/(n players alive) of remaining hp to give to revived players sounds nice, would maybe need to make sure that wont kill a player by itself if they are at 1 hp. probably should only remove max hp from player who is being revived

**Comment by jah2488** [comment]
> Hi [@jah2488](https://github.com/jah2488) , have you done any prototyping on this yet? I'm going to look at this myself soon-ish.

Hey @IntQuant, I haven't actually, got distracted by some other projects and travel.

I really like the approaches you outlined in your initial response and would be curious to see what you come up with.

**Comment by IntQuant** [comment]
Done in v0.18.0
