### ISSUE TITLE
Degraded performance from 0.15.3 -> 0.16.1

### ISSUE THREAD

**Issue by SamuelDev** [IntQuant/noita_entangled_worlds#94]
FPS is consistently <=55 on the newer version of the proxy. We reverted to 0.15.3 and its smooth again. Seems like something about the new world sync method may be causing performance degradation.

**Comment by IntQuant** [comment]
Nvm, it's certainly a problem with world sync, it takes ~12ms once in a while, which is a lot.

**Comment by IntQuant** [comment]
Should be fixed in v0.17.1, consider checking it.

**Comment by SamuelDev** [comment]
Seems good now, closing issue.
