### ISSUE TITLE
extra perk perk effect is global

### ISSUE THREAD

**Issue by bgkillas** [IntQuant/noita_entangled_worlds#97]
if you both get an the perk 'extra perk' the next shop will have 5 perks for both of you instead of 4

**Comment by Mentaleak** [comment]
in local mode it appears that every time you go to the shop there are more perks. EG we got the extra perk in the first mountain and by the bottom floor there were at least a dozen perks

**Comment by bgkillas** [comment]
you died and respawned i assume? there are a few perks like that that should be disabled

**Comment by bgkillas** [comment]
i fixed both issues in master, i think, should be fixed next release
