### ISSUE TITLE
v 0.18.0 (Local Mode) - On other player death, sound is stuck on the dead player for the host.

### ISSUE THREAD

**Issue by TTViri** [IntQuant/noita_entangled_worlds#99]
In local mode, when dying and becoming a ghost, the host player would stop experiencing sound as they normally would, instead only hearing the sounds of the area around the dead player's ghost.

Game settings were un-touched apart from switching the game mode to local mode, and the hosting method was through steam.
This occurred twice over the same run, unsure of how easy it is to reproduce.

**Comment by IntQuant** [comment]
Should be fixed in next release.
